version: '3.4'

services:
    api:
        volumes:
            - ./api/:/app
            - /app/vendor
    journal:
        build:
            args:
                app_env: dev
        volumes:
            - ./journal/:/app
            - /app/var
            - /app/vendor
