parameters:
    api_key: public
    secret: ThisTokenIsNotSoSecretChangeIt
    session_name: journal
    trusted_hosts:
      - localhost
    cache_control: private, no-cache, no-store, must-revalidate
